### PR TITLE
Auto external app navigation

### PR DESCRIPTION
**Pull request by JoePastucha**
-home-habit now navigates to profile 
-habit shows on buddy details.…
-pulls messaging app on press

### CODE REVIEW

**Review by Bongo9911 — CHANGES_REQUESTED** [review]
There's currently no clear indication that the email or phone number is a link. If you could style the email and phone number to maybe be blue with a blue underline that would be great!

I think if we could figure out how to style cards too that would be good because having each of the cards on the buddies page be a different height is pretty odd looking.

**Comment by JoePastucha** [comment]
Yeah, I agree with these ideas. Would I just go into my branch and then commit? Will that update this pull request or should I take this one down then update?

**Comment by andrewJamesBaker** [comment]
Yes, Joe, you should be able to go into your branch and update the code as it needs to be changed. Then once you commit it to your local git repo and push it to GitHub, this GitHub branch will be updated with the code in this pull request.

**Comment by andrewJamesBaker** [comment]
Works great and looks good. I am going to merge this pull request.

**Pull request merged**
