### PR TITLE
Backend work

### PR DESCRIPTION
**Pull request by JoePastucha**
Some might question the name of this branch... the answer I have for you is: "I have no idea why I named it that." I had some prep for the backend but Andrew already did it, so I just deleted my stuff and added these features:

- Fix titles so they are centered on Android
- Added hidden password (I think Kelsey did this already though)
- Added trash icon so a user can delete a buddy they don't want
- Added prompt for user to submit deletion of a buddy

### CODE REVIEW

**Comment by kny4** [comment]
We're all about deleting those lesser Buddies

**Review by kny4 — COMMENTED** [review]
Is there a way to have the icon also on the header if you navigate from the Buddies button on the home page? Same thing for the Habit Track Info Icon

**Comment by JoePastucha** [comment]
FIXED THAT! Woooooo

**Comment by Bongo9911** [comment]
Looking good! Great work!

**Pull request merged**
