### PR TITLE
Added alertBlock and Change Password page

### PR DESCRIPTION
**Pull request by Bongo9911**
These changes feature:

- An alertBlock element which when pressed brings up an alert asking you to choose between 2-3 options.
- Added content to the Account page including a Change Password block and a Log Out button.
- Created a Change Password page that asks for your Current Password and a New Password.
- Fixed bug causing switchBlocks to try and navigate you to another page.
- When tapping off the keyboard on the Habit Tracking page it will now close the keyboard.

### CODE REVIEW

**Comment by kny4** [comment]
Daaaang, Bongo! It looks sweet. 
In terms of style (which isn't necessarily a priority right now):
- I do like the blue contract. 
- Do you think the "confirm" button should more button-y?
- Should I change my login page to have the desired input text above the input containers like yours?

**Comment by Bongo9911** [comment]
> * Do you think the "confirm" button should more button-y?
I can certainly do that, the button I have there is just the default React Native button

> * Should I change my login page to have the desired input text above the input containers like yours?
I think your login page is fine as is

**Comment by kny4** [comment]
Coool! The button I used for the login page is in globalstyles under "inputButtonContainer" or something like that if you want to you/edit it so the buttons are all the same

**Comment by Bongo9911** [comment]
> So this maybe an issue on my end, but when running your branch's prototype, I am getting an error. Will send picture to slack.

Will take a look into the issue, can't test the fix since I don't have an Andorid but I'll let you know when I push a commit with a possible fix

**Review by kny4 — APPROVED** [review]
Thanks for resurrecting my kinda lame about page hahaha

**Review by JoePastucha — APPROVED** [review]

**Review by zeph01 — APPROVED** [review]
Thanks for making those changes with the styles!

**Comment by Bongo9911** [comment]
Don't merge this pull request until we get the issue with Text Inputs sorted out

**Pull request merged**
