### PR TITLE
Set up changes for the user test

### PR DESCRIPTION
**Pull request by Bongo9911**
- Signing up now leads you to a sample user no matter what info you put in
- Data is now pulled from the backend in all important places across the app

### CODE REVIEW

**Review by andrewJamesBaker — APPROVED** [review]
The branch fully changes the sign-up process for the user tests, allowing users to enter whatever information necessary during sign-up and brings the user to the sample user account. Does not affect the login process.

**Review by kny4 — APPROVED** [review]
Nice going with the sign up page

**Review by JoePastucha — APPROVED** [review]
This is perfect for all of what we need during the user tests. I will say that I am a little nervous about merging everything. Thanks, Dawson! (I do not trust myself to merge this branch js)

**Comment by JoePastucha** [comment]
nvm I am a full sender

**Pull request merged**
