### PR TITLE
Temp/habit tracking

### PR DESCRIPTION
**Pull request by zeph01**
Updated the habittrack.js file and made a new class "habittrackBlock.js" file in the shared folder.

### CODE REVIEW

**Review by andrewJamesBaker — CHANGES_REQUESTED** [review]
So I have tested the app out and it works quite well as you have described however, I would still hold out on merging this pull request until it is more truly complete. I would like to see it in a further stage of completion before it is merged or a greater explaination of the purpose of this screen.

**Comment by kny4** [comment]
@andrewJamesBaker do you think there should be some kind of instructions below the calendar feature?

**Comment by zeph01** [comment]
@andrewJamesBaker I am guessing you mean the information icon, right? I will work on that! And for the habit stack too.

**Comment by andrewJamesBaker** [comment]
My only big issue with this at the moment is that if we were asked by our stakeholders what this did when they have pulled from the master, it is not yet fully functioning. I would wait to pull it in until it is ready to be deployed, and as of this moment, it does not do anything that is helpful or functionally for the user. 

Again, I may just not totally understand the screen, and this (in general) is how it will look when we are finished, but I suspect this is not the case. 

Also, yes an info button would be nice, but not crucial if the purpose and use are self-evident.

**Pull request merged**
