### PR TITLE
updated the UI for profile page

### PR DESCRIPTION
**Pull request by JoePastucha**
- New UI 
- Added edit button to the header and created navigation
- Updated edit profile page for new UI and allow text inputs

### CODE REVIEW

**Comment by JoePastucha** [comment]
Looks like there is a small conflict with global.js. It's a simple one, but the only way I can leave the resolving conflict is with a merge and I want others to check it out first.

**Comment by kny4** [comment]
I changed the global.js to match the most updated version. Easy-peasy!

**Review by kny4 — APPROVED** [review]

**Comment by Bongo9911** [comment]
I went through and fixed some issues that occurred during the merge and removed some dependency issues. I also made it so you can tap outside of the Text Input to close the keyboard. Everything else looks good!

**Review by Bongo9911 — APPROVED** [review]

**Comment by Bongo9911** [comment]
I'm going to go ahead and merge this request since everything is good and working now

**Pull request merged**
