### PR TITLE
Added Local Storage and Login functionality

### PR DESCRIPTION
**Pull request by Bongo9911**
- Userid is now stored to the user's phone when they log in
- Upon app load, the app will check their storage to see if they have an id and if they do it will log them in
- In the Settings screen, you can now log out from the account tab
- Removed auto-capitalization from inputs like username, password, and e-mail

Check data/CommonDataManager.js to see the code for the local storage

### CODE REVIEW

**Comment by kvlinden** [comment]
It wasn't clear to me what you wanted me, specifically, to review here. The changes all seem reasonable to me.

**Comment by kny4** [comment]
Oh man...I can actually login?! (I literally had to search the sql for my password which turned out to just be 'password'...hehe

**Review by kny4 — APPROVED** [review]

**Review by andrewJamesBaker — APPROVED** [review]

**Review by JoePastucha — APPROVED** [review]
Ngl... your genius is showing...

**Pull request merged**
