### PR TITLE
Temp/update buddies profile

### PR DESCRIPTION
**Pull request by JoePastucha**
added:
- goal and category for habits
- updated buddydetails to show new information
- updated buddydetails UI to match with profile

### CODE REVIEW

**Comment by JoePastucha** [comment]
There are obviously a lot of merge conflicts, but I'll fix them up and make sure everything is all good to go!

**Review by kny4 — APPROVED** [review]
The update looks good!

**Review by Bongo9911 — APPROVED** [review]
Everything looks good! I fixed the issue on the profile page where the text didn't overflow so everything should be good now!

**Review by andrewJamesBaker — COMMENTED** [review]
Works well for me and looks really good. Good work.

**Pull request merged**
