### PR TITLE
Updated style of login and signup screens

### PR DESCRIPTION
**Pull request by kny4**
Things I updated:
* I made the font size bigger in globalStyles
* I changed the TextInput to Input for a bit of a cleaner look
* I added the hidden password feature
* I changed the last button on the Sign Up screens to 'Finish'
* I'm still working on having the option to reveal/hide the actual password text
* I'm having trouble with the style of the RNPicker, so it doesn't quite match the rest of the Input containers yet

There's one new package, so make sure to to npm install

### CODE REVIEW

**Comment by kny4** [comment]
@JoePastucha I also added a KeyBoardAwareScrollView thatautomatically scrolls the screen for you when you're typing on the keyboard. And the "Confirm Changes" button looks huge hahaha I only changed them because VanderLinden mentioned the font being small. We can revert it back though.

**Comment by kny4** [comment]
Got the eye (of Sauron?!) but it doesn't do anything yet...

**Comment by kny4** [comment]
Ok, ok, last one...

**Comment by Bongo9911** [comment]
Looks amazing

**Pull request merged**
