### PR TITLE
created login, emptyProfile, and emptyHabits

### PR DESCRIPTION
**Pull request by kny4**
- Deleted about screen from drawer
- Created general orange button and input box in globalStyles
- Created login screen with option to login or sign up. Login button takes you to home screen. Sign up button takes you to empty profile screen.

### CODE REVIEW

**Comment by kny4** [comment]
File (3)
Next button takes you to empty habits page (which I obviously don't have any vision for hahaha)
File (4)
Finish button takes you to home screen.

**Comment by kny4** [comment]
Um also, how do you attach pictures in a smaller size on GitHub comments?

**Comment by Bongo9911** [comment]
If you could make the buttons the same width and a little shorter I think it'll be perfect, other than that it looks great!

**Comment by Bongo9911** [comment]
> Um also, how do you attach pictures in a smaller size on GitHub comments?

After uploading the image move the link into something like this: 
``

**Comment by Bongo9911** [comment]
Also! Maybe change the login and sign up buttons to be all caps or just capitalize the first letter of each word.

**Comment by kny4** [comment]
I changed the button size and the capitalization

**Review by Bongo9911 — APPROVED** [review]

**Comment by JoePastucha** [comment]
I lowkey think this looks super good! Great work!

**Comment by JoePastucha** [comment]
Not sure how to (approve) but I approve

**Comment by zeph01** [comment]
Looks great to me!

**Review by zeph01 — APPROVED** [review]

**Pull request merged**
